[Feat] 온보딩 API 작성 완료
42organization/42gg-onboarding-be-renewal pull request #36
Opened 2024-12-02 03:04 UTC by seyeon22222

2024-12-02 04:53 UTC, wonies reviewed
깔끔하게 코드 잘쓰신 것 같습니다! 
@Transactional이 따로 있는 것에 대한 질문의 답을 받아 기쁩니다.
모든 제약사항을 깔끔하게 완수하신 것 같습니다! 
⭐️⭐️⭐️

2024-12-03 08:31 UTC, AreSain requested changes

2024-12-03 08:31 UTC, AreSain commented on seykim/Onboarding/src/main/java/com/sample/test/onboarding/Course/Service/CourseService.java
> +		for (Student student : students) {
students.forEach(student -> {
    StudentCourse studentCourse = studentCourseRepository.findByStudentAndCourse(student, course)
        .orElseThrow(() -> new CustomException(ErrorResponse.SUGANG_NOT_FOUND));
     student.completeCourse(course.getGrade());
    studentCourse.completeStudentCourse();
    studentRepository.save(student);
    studentCourseRepository.save(studentCourse);
});

요런식으로 한번에 작성하셔도 좋을 것 같아요

2024-12-03 08:31 UTC, AreSain commented on seykim/Onboarding/src/main/java/com/sample/test/onboarding/Data/Entity/Student.java
> +		if (this.currentGrade + grade > 15) {
리터럴 값은 최대한 지양하는것이 좋습니다

2024-12-03 08:31 UTC, AreSain commented on seykim/Onboarding/src/main/java/com/sample/test/onboarding/Student/Controller/StudentController.java
> +@RestController
Controller와 RestController가 섞여있어요! RestController로 통일하시는게 좋아보입니다.

2024-12-03 08:31 UTC, AreSain commented on seykim/Onboarding/src/main/java/com/sample/test/onboarding/Student/Controller/StudentController.java
> +		return studentService.getGraduates();
ResponseEntity 전부 사용하시는게 가독성 측면에서도 좋습니다.

2024-12-03 08:31 UTC, AreSain commented on seykim/Onboarding/src/main/java/com/sample/test/onboarding/Sugang/Controller/Dto/Request/SugangReqDto.java
> +public class SugangReqDto {
안쓰는 파일인 것 같아요

2025-01-04 11:02 UTC, closed without merging