- edit transactional
42organization/42gg-onboarding-be-renewal pull request #40
Opened 2024-12-03 08:33 UTC by wonies

2024-12-03 08:56 UTC, AreSain requested changes

2024-12-03 08:56 UTC, AreSain commented on .DS_Store
없애주세요 👍

2024-12-03 08:56 UTC, AreSain commented on src/main/java/com/example/onboarding/student/service/StudentService.java
> +		List<Sugang> sugangs = sugangRepository.findByStudent(student);
null검사 하시는게 좋을 것 같아요

2024-12-03 08:56 UTC, AreSain commented on src/main/java/com/example/onboarding/sugang/service/SugangService.java
> +	public void enroll(SugangReqDto req, int courseId) {
트랜잭션 다 써주시는게 좋을 것 같아요

2024-12-03 08:56 UTC, AreSain commented on src/main/java/com/example/onboarding/alldata/entity/Student.java
> +			if (totalGrade >= 60) {
리터럴값은 지양하시는게 좋습니다.

2024-12-03 09:21 UTC, wonies commented on src/main/java/com/example/onboarding/student/service/StudentService.java
> +		List<Sugang> sugangs = sugangRepository.findByStudent(student);
✅

2024-12-05 05:21 UTC, wonies commented on src/main/java/com/example/onboarding/alldata/entity/Student.java
> +			if (totalGrade >= 60) {
수정완료하였습니다✅

2025-01-04 06:49 UTC, closed without merging